### ISSUE TITLE
Prelaunch punch list

### ISSUE THREAD

**Issue by kmelve** [sanity-io/sanity-template-nuxt-events#1]
- [x] Image on home should take less vertical space (to prevent scroll-o-rama)
- [x] Speaker page should work without bio
- [x] Session page should have speakers (with link)
- [x] /speakers should have a nice list of speakers (avatar + name?)
- [x] speakers should be linked to in menu
- [x] move scheduled sessions to global store (to get times on all sessions items)

Due by Thursday at 4pm

**Comment by evenwestvang** [comment]
- [ ] Code of conduct page is missing styling
- [ ] Code of conduct page doesn't expand references to people in running copy (outputs `personReference` instead)
- [ ] Copy should link to events and people mentioned in running copy
